version: "3.8"
services:

  db:
    image: "postgres:13"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=coach
      - POSTGRES_PASSWORD=coach
      - POSTGRES_DB=coach
    networks:
      - coach
  backend:
    container_name: backend
    build:
      context: coach-backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - coach
networks:
  coach: